[package]
name = "calamine"
version = "0.19.1"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
repository = "https://github.com/tafia/calamine"
documentation = "https://docs.rs/calamine"
description = "An Excel/OpenDocument Spreadsheets reader and deserializer in pure rust"
license = "MIT"
readme = "README.md"
keywords = ["excel", "ods", "xls", "xlsx", "xlsb"]
categories = ["encoding", "parsing", "text-processing"]
exclude = ["tests/**/*"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
codepage = "0.1.1"
encoding_rs = "0.8.24"
log = "0.4.11"
once_cell = { version = "1.15", optional = true }
serde = "1.0.116"
quick-xml = { version = "0.25", features = ["encoding"] }
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
chrono = { version = "0.4.22", features = ["serde"], optional = true, default-features = false }

[dev-dependencies]
glob = "0.3"
env_logger = "0.9.1"
serde_derive = "1.0.116"

[features]
default = []
dates = ["chrono", "once_cell"]
